version: '3'

services:
  nginx-lb:
    image: nginx:1.25.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
      - 443:443
    networks:
      - net-servers

  server_1:
    image: nginx:1.25.1
    volumes:
      - ./indexes/index_1.html:/usr/share/nginx/html/index.html
    networks:
      - net-servers
      
  server_2:
    image: nginx:1.25.1
    volumes:
      - ./indexes/index_2.html:/usr/share/nginx/html/index.html
    networks:
      - net-servers

  server_3:
    image: nginx:1.25.1
    volumes:
      - ./indexes/index_3.html:/usr/share/nginx/html/index.html
    networks:
      - net-servers

  server_4:
    image: nginx:1.25.1
    volumes:
      - ./indexes/index_4.html:/usr/share/nginx/html/index.html
    networks:
      - net-servers
      
      
networks:
  net-servers:       
